<?php

namespace Wise\CoreBundle\Repository;

/**
 * BailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BailRepository extends \Doctrine\ORM\EntityRepository
{
}
