<?php

namespace Wise\CoreBundle\Repository;

/**
 * InterventionRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
