wise_core_homepage2:
    path:     /bail/
    defaults: { _controller: WiseCoreBundle:Default:index }

wise_core_homepage:
    path:     /
    defaults: { _controller: WiseCoreBundle:Default:homepage }

security_login_form:
    path:     /login
    defaults: { _controller: WiseCoreBundle:Security:index }
