services:
    Wise\CoreBundle\Manager\TenantManager:
        class: Wise\CoreBundle\Manager\TenantManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Wise\CoreBundle\Repository\TenantRepository'

    Wise\CoreBundle\Handler\TenantHandler:
        class: Wise\CoreBundle\Handler\TenantHandler
        arguments:
            - '@Wise\CoreBundle\Manager\TenantManager'
            - '@form.factory'
            - '@Wise\CoreBundle\Repository\TenantRepository'
        public: true

    Wise\CoreBundle\Repository\TenantRepository:
        class: Wise\CoreBundle\Repository\TenantRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['Wise\CoreBundle\Entity\Tenant']
        lazy: true

